baseURL: https://noahstride.co.uk/
title: Noah Stride
theme: marchie
googleAnalytics: G-PC65MQESZB

params:
  subtitle: "Writings & ramblings of a backend engineer."
  mode: toggle

menu:
  main:
  - name: Home
    url: "/"
    weight: 1
  - name: Blog
    url: "/blog"
    weight: 2
  - name: CV
    url: "/cv"
    weight: 3
