baseURL: https://noahstride.co.uk/
title: Noah Stride
theme: hugo-bearblog
googleAnalytics: UA-131338540-3

enableRobotsTXT: true

params:
  env: production
  description: Writings & ramblings of a backend engineer.
  title: Noah Stride
